spring.application.name=GacoSplit

# -----------------------------------------------------------
# Konfigurasi Thymeleaf (template engine)
# -----------------------------------------------------------
# prefix: lokasi folder file HTML (default: classpath:/templates/)
# suffix: ekstensi file HTML (default: .html)
# Dengan konfigurasi ini, return "index" akan memuat
# src/main/resources/templates/index.html
# -----------------------------------------------------------
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Mode cache false agar perubahan HTML langsung terlihat saat development
spring.thymeleaf.cache=false
